# Name of your application. Used to uniquely configure containers.
service: spring-boot-kamal-demo

# Name of the container image.
image: nkruk/spring-boot-kamal-demo

# Deploy to these servers.
servers:
  - 172.232.60.208

## Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder settings
builder:
  arch: amd64
  context: .

... #Other commented out stuff

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /actuator/health
  port: 8080
  max_attempts: 20
  interval: 30s